// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerApp.Data;

#nullable disable

namespace TaskManagerApp.Migrations
{
    [DbContext(typeof(TaskData))]
    [Migration("20240820144741_SeedTaskEntityData")]
    partial class SeedTaskEntityData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerApp.Models.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2024, 8, 21, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(2950),
                            Name = "Task 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2024, 8, 22, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3056),
                            Name = "Task 2",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2024, 8, 23, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3062),
                            Name = "Task 3",
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateTime(2024, 8, 24, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3068),
                            Name = "Task 4",
                            Status = 3
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateTime(2024, 8, 25, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3073),
                            Name = "Task 5",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2024, 8, 26, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3078),
                            Name = "Task 6",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateTime(2024, 8, 27, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3083),
                            Name = "Task 7",
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            DueDate = new DateTime(2024, 8, 28, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3087),
                            Name = "Task 8",
                            Status = 3
                        },
                        new
                        {
                            Id = 9,
                            DueDate = new DateTime(2024, 8, 29, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3092),
                            Name = "Task 9",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            DueDate = new DateTime(2024, 8, 30, 16, 47, 40, 185, DateTimeKind.Local).AddTicks(3098),
                            Name = "Task 10",
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
